 
name: test
on:
  pull_request:
    branches:
      - master
      - null_safety

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: |
          flutter doctor
          flutter pub get
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash)
        working-directory: ./states_rebuilder_package
      - run: |
          cd ex001_00_sync_global_and_local_state && flutter test
        working-directory: ./examples
      - run: |
          cd ex002_00_async_global_and_local_state && flutter test
        working-directory: ./examples
      - run: |
          cd ex003_00_dependent_state_management && flutter test
        working-directory: ./examples
      - run: |
          cd ex004_00_navigation && flutter test
        working-directory: ./examples
      - run: |
          cd ex005_00_crud_operations && flutter test
        working-directory: ./examples
      - run: |
          cd ex006_00_authentication_and_authorization && flutter test
        working-directory: ./examples
      - run: |
          cd ex007_00_app_theme_management && flutter test
        working-directory: ./examples
      - run: |
          cd ex008_00_app_i18n_i10n && flutter test
        working-directory: ./examples
      - run: |
          cd ex009_00_animation && flutter test
        working-directory: ./examples
      - run: |
          cd ex010_00_form_fields && flutter test
        working-directory: ./examples
      - run: |
          cd ex_001_2_flutter_default_counter_app_with_functional_injection && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_002_2_form_validation_with_reactive_model_with_functional_injection && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_004_2_countdown_timer_with_functional_injection && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_005_theme_switching && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_006_1_crud_app && flutter test
        working-directory: ./examples/others

      - run: |
          cd ex_007_2_clean_architecture_dane_mackier_app_with_fi && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_008_clean_architecture_firebase_login && flutter test
        working-directory: ./examples/others
      - run: |
          cd ex_009_1_4_ca_todo_mvc_with_state_persistence_and_user_auth && flutter test
        working-directory: ./examples/others
      # - run: cd examples/ex_000_hello_world && flutter test
      # - run: cd examples/ex_009_1_2_ca_todo_mvc_cloud_firestore_immutable_with_fi && flutter test
      # - run: cd examples/ex_009_1_2_ca_todo_mvc_cloud_firestore_immutable_with_fi && flutter test
      # - run: cd examples/ex_009_2_2_ca_todo_mvc_mutable_with_fi && flutter test
      # # - run: cd examples/ex_009_3_2_todo_mvc_the_flutter_bloc_way_with_fi && flutter test
      # - run: cd examples/ex_010_clean_architecture_multi_counter_realtime_firebase && flutter test
      # - run: cd examples/ex_011_github_search_app && flutter test
      # - run: cd states_rebuilder_package && flutter test --coverage
      # - run: bash <(curl -s https://codecov.io/bash)
